---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bankapp-statefulset
spec:
  serviceName: "bankapp-service"
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp-container
        image: shaikmustafa/charan:db
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: bankapp-db-secret
        - configMapRef:
            name: bankapp-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi 
