apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: shankar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: mysecret
      containers:
        - name: cont-1
          image: shankarnarayana/clientapp:appimage
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "200m"
              memory: "100Mi"
